inf=input('Digite algo: ')
print('O tipo primitivo desse valor é ',type(inf))
print('É numérico ? {}'.format(inf.isnumeric()))
print('É alfanumérico ? {}'.format(inf.isalnum()))
print('É alfabético ? {}'.format(inf.isalpha()))
print('Tem letras maiúsuclas ? {}'.format(inf.isupper()))
print('Tem letras minúsuclas ? {}'.format(inf.islower()))
print('Só tem espaços ? {}'.format(inf.isspace()))
print('Está capitalizada ? {}'.format(inf.istitle()))
